Workflow:
  - trollflow.examples.readers.txt_reader.TXTFileReader:
      in_file:
        uri: /tmp/test.txt

  - trollflow.examples.transformers.capitalizer.Capitalizer:
      in_file:
      out_file:

  - trollflow.examples.writers.txt_writer.TXTFileWriter:
      out_file:
        uri: /tmp/test_cap.txt
